In [111]:
from bs4 import BeautifulSoup as bs
import requests
import re
import pandas as pd
import numpy as np

In [4]:
url = "https://www.meraparivar.org/financial-accounts/"
response = requests.get(url)

In [6]:
html = response.content

In [8]:
soup = bs(html, "html.parser")

In [9]:
print(soup)

<!DOCTYPE html>

<html lang="en-US" prefix="og: https://ogp.me/ns#">
<head>
<meta charset="utf-8"/>
<!-- Search Engine Optimization by Rank Math - https://rankmath.com/ -->
<title>Financial Accounts - Meraparivar</title>
<meta content="Financial Audit Report 2022-2023 Financial Audit Report 2021-2022 Financial Audit Report 2020-2021 Financial Audit Report 2019-2020 Financial Audit Report" name="description">
<meta content="index, follow, max-snippet:-1, max-video-preview:-1, max-image-preview:large" name="robots"/>
<link href="https://www.meraparivar.org/financial-accounts/" rel="canonical"/>
<meta content="en_US" property="og:locale"/>
<meta content="article" property="og:type"/>
<meta content="Financial Accounts - Meraparivar" property="og:title"/>
<meta content="Financial Audit Report 2022-2023 Financial Audit Report 2021-2022 Financial Audit Report 2020-2021 Financial Audit Report 2019-2020 Financial Audit Report" property="og:description"/>
<meta content="https://www.meraparivar.o

In [18]:
table = soup.find_all('table', class_ = "tablepress tablepress-id-1")

In [19]:
table

[<table class="tablepress tablepress-id-1" id="tablepress-1">
 <thead>
 <tr class="row-1 odd">
 <th class="column-1">Date</th><th class="column-2">Donor</th><th class="column-3">Purpose</th><th class="column-4">Amount</th><th class="column-5"></th>
 </tr>
 </thead>
 <tbody class="row-hover">
 <tr class="row-2 even">
 <td class="column-1">7/5/2018</td><td class="column-2">itwillbe</td><td class="column-3"></td><td class="column-4">402553</td><td class="column-5"></td>
 </tr>
 <tr class="row-3 odd">
 <td class="column-1">8/5/2018</td><td class="column-2">Operation blessing</td><td class="column-3"></td><td class="column-4">75000</td><td class="column-5"></td>
 </tr>
 <tr class="row-4 even">
 <td class="column-1">25/5/2018</td><td class="column-2">operation blessing</td><td class="column-3"></td><td class="column-4">75000</td><td class="column-5"></td>
 </tr>
 <tr class="row-5 odd">
 <td class="column-1">28/6/2018</td><td class="column-2">operation blessing</td><td class="column-3"></td><

In [97]:
data = {}
for i in range(1,6):
    columna = table[0].find_all('th', class_ = f"column-{i}")[0].text
    if columna != '':
        data[columna] = []
    else:
        data['Country'] = []

In [98]:
data

{'Date': [], 'Donor': [], 'Purpose': [], 'Amount': [], 'Country': []}

In [99]:
for index, i in enumerate(data.keys()):
    columna_elementos = table[0].find_all('td', class_ = f"column-{index+1}")
    for a in columna_elementos:
        data[i].append(a.text)

In [359]:
for i in data:
    print(i)
    print(len(data[i]))

Date
200
Donor
200
Purpose
200
Amount
200
Country
200


In [668]:
df = pd.DataFrame(data)

In [669]:
df

Date               Donor Purpose  Amount Country
0     7/5/2018            itwillbe          402553        
1     8/5/2018  Operation blessing           75000        
2    25/5/2018  operation blessing           75000        
3    28/6/2018  operation blessing           75000        
4     8/8/2018            itwillbe          324808        
..         ...                 ...     ...     ...     ...
195                                                       
196                                                       
197                                                       
198                                                       
199                                                       

[200 rows x 5 columns]

In [670]:
df[df['Date'] == '']

Date Donor Purpose Amount Country
109                                  
110                                  
111                                  
112                                  
113                                  
..   ...   ...     ...    ...     ...
195                                  
196                                  
197                                  
198                                  
199                                  

[91 rows x 5 columns]

In [671]:
df_filtrado = df.loc[:108]

In [672]:
df_filtrado.replace('', np.nan, inplace=True)

C:\Users\Mega Tecnologia\AppData\Local\Temp\ipykernel_1672\1768429897.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtrado.replace('', np.nan, inplace=True)


In [673]:
df_filtrado = df_filtrado.applymap(lambda x: x.lower() if isinstance(x, str) else x)

C:\Users\Mega Tecnologia\AppData\Local\Temp\ipykernel_1672\631455714.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_filtrado = df_filtrado.applymap(lambda x: x.lower() if isinstance(x, str) else x)


In [674]:
df_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Date     109 non-null    object
 1   Donor    109 non-null    object
 2   Purpose  95 non-null     object
 3   Amount   108 non-null    object
 4   Country  35 non-null     object
dtypes: object(5)
memory usage: 4.4+ KB


In [675]:
df_filtrado['Date'].loc[5]

'18/8/18'

In [676]:
reemplazos = {'18/8/18': '18/08/2018', 
'24/8/18': '24/08/2018', 
'16/102018':'16/10/2018',
'26/03/19':'26/03/2019', 
'17/05/19':'17/05/2019',
'23/05/19':'23/05/2019', 
'18/06/19':'18/06/2019',
'20/06/19':'20/06/2019', 
'09/07/19':'09/07/2019',
'24/07/19':'24/07/2019',
'29/07/19':'29/07/2019', 
'6/11/19':'06/11/2019', 
'2/12/19':'02/12/2019', 
'7/12/19':'07/12/2019', 
'20/12/19':'20/12/2019',
'13/5 2020':'13/05/2020', 
'2/7/20':'02/07/2020', 
'27/10.2020':'27/10/2020', 
'23/11/20':'23/11/2020', 
'16/12/20':'16/12/2020',
'1812/20':'18/12/2020', 
'3/5/21':'03/05/2021', 
'20/5/21':'20/05/2021', 
'21/5/21':'21/5/2021', 
'2/6/21':'02/06/2021', 
'24/6/21':'24/06/2021',
'30/7/21':'30/07/2021', 
'11/8/21':'11/08/2021', 
'6/10/21':'06/10/2021', 
'14/10/21':'14/10/2021', 
'20/10/21':'20/10/2021',
'17/11/21':'17/11/2021', 
'23/11/21':'23/11/2021', 
'28/12/21':'28/12/2021', 
'9/3/22':'09/03/2022', 
'22/03/22':'22/03/2022',
'29/03/22':'29/03/2022', 
'30/03/22':'30/03/2022', 
'19/05/22':'19/05/2022', 
'01/06/22':'01/06/2022', 
'22/06/22':'22/06/2022',
'27/06/22':'27/06/2022'}

In [677]:
df_filtrado['Date'].replace(reemplazos, inplace=True)

In [678]:
df_filtrado['Date'] = pd.to_datetime(df_filtrado['Date'], format="%d/%m/%Y")

In [679]:
df_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype         
---  ------   --------------  -----         
 0   Date     109 non-null    datetime64[ns]
 1   Donor    109 non-null    object        
 2   Purpose  95 non-null     object        
 3   Amount   108 non-null    object        
 4   Country  35 non-null     object        
dtypes: datetime64[ns](1), object(4)
memory usage: 4.4+ KB


In [680]:
df_filtrado['Donor'].unique()

array(['itwillbe', 'operation blessing',
       'foundation international research education', 'imn usa',
       'itwillbe spain', 'street of india spain',
       'community justice swden', 'street of india', 'streets of india',
       'paypal payment', 'it will be', 'operation blessing india',
       'foundation d enterprise decathlon', 'smile foundation',
       'itwillbw', 'community for justic', 'netscribes india',
       'streets ofindia', 'street of  india', 'itwill be', 'global assis'],
      dtype=object)

In [681]:
df_filtrado.loc[df_filtrado['Donor'].str.contains('spain'), 'Country'] = 'spain'

In [682]:
df_filtrado.loc[df_filtrado['Donor'].str.contains('usa'), 'Country'] = 'usa'

In [683]:
df_filtrado.loc[df_filtrado['Donor'].str.contains('swden'), 'Country'] = 'sweden'

In [684]:
df_filtrado.loc[df_filtrado['Donor'].str.contains('india') & df_filtrado['Country'].isna(), 'Country'] = 'india'

In [685]:
palabras_claves = {
    'will' : 'it will be',
    'stree' : 'streets of india',
    'imn' : 'imn',
    'community' : 'community justice',
    'blessing' : 'operation blessing'
}

In [686]:
for i in palabras_claves:
    df_filtrado['Donor'] = df_filtrado['Donor'].apply(lambda x: palabras_claves[i] if i in x else x)

In [687]:
df_filtrado['Donor'].unique()

array(['it will be', 'operation blessing',
       'foundation international research education', 'imn',
       'streets of india', 'community justice', 'paypal payment',
       'foundation d enterprise decathlon', 'smile foundation',
       'netscribes india', 'global assis'], dtype=object)

In [688]:
df_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype         
---  ------   --------------  -----         
 0   Date     109 non-null    datetime64[ns]
 1   Donor    109 non-null    object        
 2   Purpose  95 non-null     object        
 3   Amount   108 non-null    object        
 4   Country  58 non-null     object        
dtypes: datetime64[ns](1), object(4)
memory usage: 4.4+ KB


In [689]:
df_filtrado['Purpose'].unique()

array([nan, 'medical clinic', 'children education',
       'skill development project', 'school building',
       'informal education', 'children project', 'children',
       'children emergency relief', 'covid-19 work children project',
       'covid 19 work children project', 'children education/ food',
       'foodbank counselling', 'children education /food',
       'children project food', 'children food covid',
       'foodbank coiunselling', 'foodbank /counselling',
       'educational project', 'swabhiman project(teen challenge)',
       'food bank counselling', 'education project', 'foodbank/education',
       'education', 'relief', 'medical refief', 'relief work',
       'education/ food', 'education/food', 'counselling teen boys',
       'foodbank and education',
       'education/skill programme/ women empowerment',
       'education/compter/ swing', 'food bank', 'charity purpose',
       'charity/community purpose'], dtype=object)

In [690]:
df_filtrado['Purpose'] = df_filtrado['Purpose'].str.replace('refief', 'relief')

In [691]:
df_filtrado['Purpose'].unique()

array([nan, 'medical clinic', 'children education',
       'skill development project', 'school building',
       'informal education', 'children project', 'children',
       'children emergency relief', 'covid-19 work children project',
       'covid 19 work children project', 'children education/ food',
       'foodbank counselling', 'children education /food',
       'children project food', 'children food covid',
       'foodbank coiunselling', 'foodbank /counselling',
       'educational project', 'swabhiman project(teen challenge)',
       'food bank counselling', 'education project', 'foodbank/education',
       'education', 'relief', 'medical relief', 'relief work',
       'education/ food', 'education/food', 'counselling teen boys',
       'foodbank and education',
       'education/skill programme/ women empowerment',
       'education/compter/ swing', 'food bank', 'charity purpose',
       'charity/community purpose'], dtype=object)

In [692]:
df_filtrado = df_filtrado.assign(
    medical=lambda x: (x['Purpose'].str.contains('medical') & ~x['Purpose'].isna()).astype(int),
    children=lambda x: (x['Purpose'].str.contains('children') & ~x['Purpose'].isna()).astype(int),
    education=lambda x: (x['Purpose'].str.contains('education') & ~x['Purpose'].isna()).astype(int),
    skill_development_project=lambda x: (x['Purpose'].str.contains('skill') & ~x['Purpose'].isna()).astype(int),
    building=lambda x: (x['Purpose'].str.contains('building') & ~x['Purpose'].isna()).astype(int),
    relief=lambda x: (x['Purpose'].str.contains('relief') & ~x['Purpose'].isna()).astype(int),
    covid_19=lambda x: (x['Purpose'].str.contains('covid') & ~x['Purpose'].isna()).astype(int),
    foodbank=lambda x: (x['Purpose'].str.contains('bank') & ~x['Purpose'].isna()).astype(int),
    food=lambda x: (x['Purpose'].str.contains('food') & ~x['Purpose'].isna()).astype(int),
    teen=lambda x: (x['Purpose'].str.contains('teen') & ~x['Purpose'].isna()).astype(int),
    women_empowerment=lambda x: (x['Purpose'].str.contains('women') & ~x['Purpose'].isna()).astype(int),
    charity=lambda x: (x['Purpose'].str.contains('charity') & ~x['Purpose'].isna()).astype(int),
    community=lambda x: (x['Purpose'].str.contains('community') & ~x['Purpose'].isna()).astype(int),
    non_reg_purpose=lambda x: (x['Purpose'].isna()).astype(int)
)


In [693]:
columnas_de_interes = ['medical', 'children', 'education', 'skill_development_project', 'building', 
                       'relief', 'covid_19', 'foodbank', 'food', 'teen', 'women_empowerment', 'charity', 
                       'community']

filas_con_nan = df_filtrado[(df_filtrado[columnas_de_interes] == 0).all(axis=1)]

In [694]:
filas_con_nan

Date                                        Donor Purpose   Amount  \
0  2018-05-07                                   it will be     NaN   402553   
1  2018-05-08                           operation blessing     NaN    75000   
2  2018-05-25                           operation blessing     NaN    75000   
3  2018-06-28                           operation blessing     NaN    75000   
4  2018-08-08                                   it will be     NaN   324808   
5  2018-08-18                           operation blessing     NaN   217500   
6  2018-08-24                           operation blessing     NaN     9700   
7  2018-09-10                           operation blessing     NaN    70000   
8  2018-10-16  foundation international research education     NaN  1802664   
9  2018-10-22                                   it will be     NaN   266165   
10 2018-10-25                           operation blessing     NaN    57500   
11 2018-11-01                           operation blessing     NaN    57500   
12 2018-11-21                           operation blessing     NaN    57500   
13 2018-12-03                           operation blessing     NaN    72500   

   Country  medical  children  education  skill_development_project  building  \
0      NaN        0         0          0                          0         0   
1      NaN        0         0          0                          0         0   
2      NaN        0         0          0                          0         0   
3      NaN        0         0          0                          0         0   
4      NaN        0         0          0                          0         0   
5      NaN        0         0          0                          0         0   
6      NaN        0         0          0                          0         0   
7      NaN        0         0          0                          0         0   
8      NaN        0         0          0                          0         0   
9      NaN        0         0          0                          0         0   
10     NaN        0         0          0                          0         0   
11     NaN        0         0          0                          0         0   
12     NaN        0         0          0                          0         0   
13     NaN        0         0          0                          0         0   

    relief  covid_19  foodbank  food  teen  women_empowerment  charity  \
0        0         0         0     0     0                  0        0   
1        0         0         0     0     0                  0        0   
2        0         0         0     0     0                  0        0   
3        0         0         0     0     0                  0        0   
4        0         0         0     0     0                  0        0   
5        0         0         0     0     0                  0        0   
6        0         0         0     0     0                  0        0   
7        0         0         0     0     0                  0        0   
8        0         0         0     0     0                  0        0   
9        0         0         0     0     0                  0        0   
10       0         0         0     0     0                  0        0   
11       0         0         0     0     0                  0        0   
12       0         0         0     0     0                  0        0   
13       0         0         0     0     0                  0        0   

    community  non_reg_purpose  
0           0                1  
1           0                1  
2           0                1  
3           0                1  
4           0                1  
5           0                1  
6           0                1  
7           0                1  
8           0                1  
9           0                1  
10          0                1  
11          0                1  
12          0                1  
13          0                1

In [695]:
df_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype         
---  ------                     --------------  -----         
 0   Date                       109 non-null    datetime64[ns]
 1   Donor                      109 non-null    object        
 2   Purpose                    95 non-null     object        
 3   Amount                     108 non-null    object        
 4   Country                    58 non-null     object        
 5   medical                    109 non-null    int32         
 6   children                   109 non-null    int32         
 7   education                  109 non-null    int32         
 8   skill_development_project  109 non-null    int32         
 9   building                   109 non-null    int32         
 10  relief                     109 non-null    int32         
 11  covid_19                   109 non-null    int32         
 12  foodbank

In [696]:
df_filtrado['Amount'].unique()

array(['402553', '75000', '324808', '217500', '9700', '70000', '1802664',
       '266165', '57500', '72500', '145000', '170500', '1413931',
       '668383', '392801', '76000', '1366589', '442751', '152275',
       '96420', '94257', '46500', '111500', '73515', '40796', '98583',
       '71460', '45407', '142920 inr', '2045euro', '719 inr', '2000 euro',
       '245351 inr', '15126', '6950', '50500', '3000 euro', '2960 euro',
       '668', '11041', '2381 euro', '394351 inr', '51000 inr',
       '50000 inr', '171521 inr', '13570 inr', '3385 inr', '1680 inr',
       '51000', '1545', '6900 euro', '174410 inr', '2000euro',
       '409351inr', '300000inr', '549351 inr', '504251 inr', '261725 inr',
       '176351 inr', '174720 inr', '172715 inr', '518334 inr',
       '261419 inr', '5 184.80 euro', '345400 inr', '237901 inr',
       'euro2285', 'euro 990', '249187 inr', '246442 inr', '409568 inr',
       '163068 inr', '165900 inr', '399896 inr', '72446 inr',
       '200638 inr', '152987 inr', '15

In [697]:
df_filtrado['Amount'].fillna(value = '0', inplace = True)

In [698]:
df_filtrado[df_filtrado['Amount'] == '11041']

Date           Donor                         Purpose Amount Country  \
56 2020-05-29  paypal payment  covid-19 work children project  11041     NaN   

    medical  children  education  skill_development_project  building  relief  \
56        0         1          0                          0         0       0   

    covid_19  foodbank  food  teen  women_empowerment  charity  community  \
56         1         0     0     0                  0        0          0   

    non_reg_purpose  
56                0

In [699]:
df_filtrado['Amount'].unique()

array(['402553', '75000', '324808', '217500', '9700', '70000', '1802664',
       '266165', '57500', '72500', '145000', '170500', '1413931',
       '668383', '392801', '76000', '1366589', '442751', '152275',
       '96420', '94257', '46500', '111500', '73515', '40796', '98583',
       '71460', '45407', '142920 inr', '2045euro', '719 inr', '2000 euro',
       '245351 inr', '15126', '6950', '50500', '3000 euro', '2960 euro',
       '668', '11041', '2381 euro', '394351 inr', '51000 inr',
       '50000 inr', '171521 inr', '13570 inr', '3385 inr', '1680 inr',
       '51000', '1545', '6900 euro', '174410 inr', '2000euro',
       '409351inr', '300000inr', '549351 inr', '504251 inr', '261725 inr',
       '176351 inr', '174720 inr', '172715 inr', '518334 inr',
       '261419 inr', '5 184.80 euro', '345400 inr', '237901 inr',
       'euro2285', 'euro 990', '249187 inr', '246442 inr', '409568 inr',
       '163068 inr', '165900 inr', '399896 inr', '72446 inr',
       '200638 inr', '152987 inr', '15

In [700]:
df_filtrado['value_amount'] = df_filtrado['Amount'].str.extract(r'(\d+)')

In [701]:
df_filtrado['value_amount'].unique()

array(['402553', '75000', '324808', '217500', '9700', '70000', '1802664',
       '266165', '57500', '72500', '145000', '170500', '1413931',
       '668383', '392801', '76000', '1366589', '442751', '152275',
       '96420', '94257', '46500', '111500', '73515', '40796', '98583',
       '71460', '45407', '142920', '2045', '719', '2000', '245351',
       '15126', '6950', '50500', '3000', '2960', '668', '11041', '2381',
       '394351', '51000', '50000', '171521', '13570', '3385', '1680',
       '1545', '6900', '174410', '409351', '300000', '549351', '504251',
       '261725', '176351', '174720', '172715', '518334', '261419', '5',
       '345400', '237901', '2285', '990', '249187', '246442', '409568',
       '163068', '165900', '399896', '72446', '200638', '152987',
       '153333', '321680', '168066', '155009', '158880', '2698553', '0'],
      dtype=object)

In [702]:
df_filtrado.loc[df_filtrado['value_amount'] == '5', 'value_amount'] = '5184'

In [703]:
df_filtrado['value_amount'] = df_filtrado['value_amount'].astype(int)

In [704]:
df_filtrado['value_amount'].unique()

array([ 402553,   75000,  324808,  217500,    9700,   70000, 1802664,
        266165,   57500,   72500,  145000,  170500, 1413931,  668383,
        392801,   76000, 1366589,  442751,  152275,   96420,   94257,
         46500,  111500,   73515,   40796,   98583,   71460,   45407,
        142920,    2045,     719,    2000,  245351,   15126,    6950,
         50500,    3000,    2960,     668,   11041,    2381,  394351,
         51000,   50000,  171521,   13570,    3385,    1680,    1545,
          6900,  174410,  409351,  300000,  549351,  504251,  261725,
        176351,  174720,  172715,  518334,  261419,    5184,  345400,
        237901,    2285,     990,  249187,  246442,  409568,  163068,
        165900,  399896,   72446,  200638,  152987,  153333,  321680,
        168066,  155009,  158880, 2698553,       0])

In [705]:
# df_filtrado.loc[df_filtrado['Amount'].str.contains('inr'), 'value_amount'] *= 0.011

In [706]:
df_filtrado['value_amount'].unique()

array([ 402553,   75000,  324808,  217500,    9700,   70000, 1802664,
        266165,   57500,   72500,  145000,  170500, 1413931,  668383,
        392801,   76000, 1366589,  442751,  152275,   96420,   94257,
         46500,  111500,   73515,   40796,   98583,   71460,   45407,
        142920,    2045,     719,    2000,  245351,   15126,    6950,
         50500,    3000,    2960,     668,   11041,    2381,  394351,
         51000,   50000,  171521,   13570,    3385,    1680,    1545,
          6900,  174410,  409351,  300000,  549351,  504251,  261725,
        176351,  174720,  172715,  518334,  261419,    5184,  345400,
        237901,    2285,     990,  249187,  246442,  409568,  163068,
        165900,  399896,   72446,  200638,  152987,  153333,  321680,
        168066,  155009,  158880, 2698553,       0])

In [707]:
valores_redondeados = (df_filtrado.loc[df_filtrado['Amount'].str.contains('inr'), 'value_amount'] * 0.011).round()

In [708]:
valores_redondeados

43     1572.00
45        8.00
47     2699.00
62     4338.00
63      561.00
64      550.00
65     1887.00
66      149.00
67       37.00
68       18.00
74     1919.00
76     4503.00
77     3300.00
79     6043.00
81     5547.00
82     2879.00
83     1940.00
84     1922.00
85     1900.00
86     5702.00
87     2876.00
89     3799.00
90     2617.00
93     2741.00
94     2711.00
95     4505.00
96     1794.00
97     1825.00
98     4399.00
99      797.00
100    2207.00
101    1683.00
102    1687.00
103    3538.00
104    1849.00
105    1705.00
106    1748.00
107   29684.00
Name: value_amount, dtype: float64

In [709]:
df_filtrado.loc[df_filtrado['Amount'].str.contains('inr'), 'value_amount'] = valores_redondeados

In [710]:
df_filtrado['value_amount'].unique()

array([ 402553,   75000,  324808,  217500,    9700,   70000, 1802664,
        266165,   57500,   72500,  145000,  170500, 1413931,  668383,
        392801,   76000, 1366589,  442751,  152275,   96420,   94257,
         46500,  111500,   73515,   40796,   98583,   71460,   45407,
          1572,    2045,       8,    2000,    2699,   15126,    6950,
         50500,    3000,    2960,     668,   11041,    2381,    4338,
           561,     550,    1887,     149,      37,      18,   51000,
          1545,    6900,    1919,    4503,    3300,    6043,    5547,
          2879,    1940,    1922,    1900,    5702,    2876,    5184,
          3799,    2617,    2285,     990,    2741,    2711,    4505,
          1794,    1825,    4399,     797,    2207,    1683,    1687,
          3538,    1849,    1705,    1748,   29684,       0])

In [711]:
df_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype         
---  ------                     --------------  -----         
 0   Date                       109 non-null    datetime64[ns]
 1   Donor                      109 non-null    object        
 2   Purpose                    95 non-null     object        
 3   Amount                     109 non-null    object        
 4   Country                    58 non-null     object        
 5   medical                    109 non-null    int32         
 6   children                   109 non-null    int32         
 7   education                  109 non-null    int32         
 8   skill_development_project  109 non-null    int32         
 9   building                   109 non-null    int32         
 10  relief                     109 non-null    int32         
 11  covid_19                   109 non-null    int32         
 12  foodbank

In [712]:
df_filtrado['Country'].replace('swden', 'sweden', inplace = True)

In [713]:
df_filtrado['Country'].unique()

array([nan, 'usa', 'spain', 'sweden', 'india'], dtype=object)

In [714]:
df_filtrado.to_csv('df_filtrao_limpio.csv')